model:
  _target_: vam.action_expert.ActionLearning
  _recursive_: false
  flow_sampling: beta
  flow_alpha: 1.5
  flow_beta: 1.0
  vam_conf:
    _target_: vam.action_expert.VideoActionModel
    _recursive_: false
    finetuning_timesteps: ${data.sequence_length}
    num_inference_steps: 10
    flow_sig_min: 0.001
    final_action_clip_value: null
    action_scaling: 70.0
    gpt_mup_base_shapes: ./mup_shapes/gpt2_24layers_basewidth256.bsh
    gpt_checkpoint_path: /raid/zengchaolv/shuaizhe_vavam/VideoActionModel/inference/finetune_output/VaViM_768_matrix_clean0_ep002/checkpoints/vavim_clean0_ep002_fused.pt
    gpt_config:
      _target_: vam.video_pretraining.MupGPT2
      embedding_dim: 768
      dim_heads: 128
      nb_layers: 24
      mlp_dim_mult: 4
      vocabulary_size: 16385
      nb_timesteps: 8
      nb_tokens_per_timestep: 576
      output_tied: true
    action_mup_base_shapes: ./mup_shapes/actionexpert_24layers_baseattentiondim256_baseembeddingdim64.bsh
    action_checkpoint_path: null
    action_config:
      _target_: vam.action_expert.MupActionExpert
      embedding_dim: 64
      attention_dim: 768
      action_dim: 2
      action_horizon: ${data.action_length}
      number_high_level_command: 3
      dim_heads: ${model.vam_conf.gpt_config.dim_heads}
      nb_layers: ${model.vam_conf.gpt_config.nb_layers}
      init_std: 0.01
  optimizer_conf:
    lr: 0.0001
    weight_decay: 1.0e-08
    betas:
    - 0.9
    - 0.95
    eps: 1.0e-08
    decoupled_wd: true
model/params/total: 188419648
model/params/trainable: 5518144
model/params/non_trainable: 182901504
paths:
  output_dir: /raid/zengchaolv/shuaizhe_vavam/VideoActionModel/inference/finetune_output
  data_root_dir: /lustre/fsn1/projects/rech/ycy/commun/nuplan/sensor_blobs/
  pickle_path: /lustre/fswork/projects/rech/ycy/commun/nuplan_pickling/generated_files/
  quantized_data_root_dir: /lustre/fsn1/projects/rech/ycy/commun/nuplan_tokenized/VQGAN_ImageNet_f16_1024
data:
  _target_: vam.datalib.EgoTrajectoryDataModule
  nuplan_tokens_rootdir: null
  nuscenes_tokens_rootdir: /raid/zengchaolv/sz/vavim_finetune_nuscenes/data/tokens_new
  nuplan_train_pickle_path: null
  nuscenes_train_pickle_path: /raid/zengchaolv/sz/vavim_finetune_nuscenes/data/nuscenes_train_data_cleaned.pkl
  nuplan_val_pickle_path: null
  nuscenes_val_pickle_path: /raid/zengchaolv/sz/vavim_finetune_nuscenes/data/nuscenes_val_data_cleaned.pkl
  sequence_length: 8
  action_length: 6
  batch_size: 4
  num_workers: 0
trainer:
  _target_: lightning.pytorch.trainer.Trainer
  default_root_dir: ${paths.output_dir}/${name}/
  min_epochs: 1
  max_epochs: 1
  accelerator: gpu
  devices: 8
  precision: bf16-mixed
  check_val_every_n_epoch: 1
  deterministic: false
  num_sanity_val_steps: 0
  strategy: deepspeed_stage_2
  num_nodes: 1
  sync_batchnorm: true
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  log_every_n_steps: 5
scheduler:
  _target_: vam.utils.WarmupStableDrop
  warmup_iter: 5
  end_iter: 595
  drop_iter: 535
  num_iter: 0
  is_finetuning: false
callbacks:
  model_summary:
    _target_: lightning.pytorch.callbacks.ModelSummary
    max_depth: 2
  progress_bar:
    _target_: lightning.pytorch.callbacks.TQDMProgressBar
    refresh_rate: 5
  learning_rate_monitor:
    _target_: lightning.pytorch.callbacks.LearningRateMonitor
    logging_interval: step
  device_stats_monitor:
    _target_: lightning.pytorch.callbacks.DeviceStatsMonitor
  trajectory_logging: null
  before_drop_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: ${paths.output_dir}/${name}/checkpoints/
    filename: before_drop_{epoch:03d}_{step:010d}
    every_n_train_steps: 6525
    verbose: true
  half_epoch_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: ${paths.output_dir}/${name}/checkpoints/
    filename: quarters_{epoch:03d}_{step:010d}
    every_n_train_steps: 3625
    save_top_k: -1
    verbose: true
  last_hours_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: ${paths.output_dir}/${name}/checkpoints/
    filename: last_hours_{epoch:03d}_{step:010d}
    save_top_k: 1
    train_time_interval:
      _target_: datetime.timedelta
      hours: 1
    verbose: true
  end_of_epoch_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: ${paths.output_dir}/${name}/checkpoints/
    filename: end_of_epoch_{epoch:03d}_{step:010d}
    save_last: true
    every_n_epochs: 1
    verbose: true
name: VAM_action_matrix_from_clean0_ep002
seed: 84924
training_device: NVIDIA A100-SXM4-40GB
git_sha: 738050ec7000fc23b7af0c3ca14693d75abb056e
